#+HUGO_BASE_DIR: ~/Stuff/Code/blog/
#+HUGO_SECTION: posts

* DONE Hello world!
CLOSED: [2020-05-17 Sun 22:02]
:PROPERTIES:
:EXPORT_FILE_NAME: hello-world
:END:
First post! I've finally decided to return to blogging, or at least to give it a try. The idea is to document my ideas, projects and failures.

I'll be using [[https://gohugo.io/][Hugo]] to generate the site and [[https://help.github.com/en/github/working-with-github-pages][GitHub's pages]] to host it.

* DONE Blogging workflow                                               :blog:
  CLOSED: [2021-01-09 Sat 18:55]
  :PROPERTIES:
  :EXPORT_FILE_NAME: blogging-workflow
  :END:
  I'm still trying to figure out the best workflow for me, for now I'm using [[https://www.gnu.org/software/emacs/][Emacs]] with [[https://orgmode.org/][Org mode]], the package that generates the Markdown from the org files is called [[https://ox-hugo.scripter.co/][ox-hugo]]. I'm using the development version of [[https://www.spacemacs.org/][Spacemacs]] and the installation was super easy. My configuration looks like this:
  #+begin_src emacs-lisp
  dotspacemacs-configuration-layers
  '(
    (org :variables
         org-want-todo-bindings t
         org-enable-hugo-support t)
   )
   #+end_src
   
   All the posts (blogs entries) are in one file, as recommended by ox-hugo, each entry is a todo. The reason for that is that once the status changes to done, the date is recorded. This is quite handy to date the entries once you are done writing them.

   For the hosting I'm using two repositories, the output which is basically the HTML part (that's the public/ directory in the Hugo structure) and the rest in a separate repository.

* DONE Installing Slackware on a Raspberry PI4                       :arm:pi:
  CLOSED: [2021-01-22 Fri 20:16]
  :PROPERTIES:
  :EXPORT_FILE_NAME: sarpi
  :END:
  I believe ARM architecture to be the future; and while I wait for the [[https://www.khadas.com/vim3][Khadas VIM3]] to arrive I thought it may be a good idea to see if the Raspberry Pi could replace my desktop (I hope to achieve that with the VIM3). My Linux distribution of choice is [[http://www.slackware.com/][Slackware]], one of the many reasons that I like it for, is that you get a sort of two distros in one: It can be a rolling distribution (just like [[https://archlinux.org/][Arch Linux]]) or a fixed one. This allows me to get the rolling one (which is called -current and gets updated almost daily) on my desktop to enjoy the latest version of everything, while having a more stable one (fixed version) like 14.4 on my NAS server.

  Slackware has an official ARM port for 32bits and the work for a 64bits version (aarch64) has already started, so the timing is perfect. I have a Raspberry Pi 4 with 4MB or RAM. The installation is possible thanks to the great work of the [[https://sarpi.fatdog.eu/][SARPi project]], SARPi packs the binary files from the Raspberry foundation, the kernel and configurations files in a way that works with the official installation.

  The installation was smooth following the excellent documentation of the SARPi project, the only issue for me was that I didn't want to download an ISO or mirror the repository as a source for installation. Network installation is of course possible, but I was away from my router and the packages required for a WPA wireless connection are not available in the installer. However, it just a matter of pulling the missing packages over an usb drive from the [[ftp://ftp.arm.slackware.com/slackwarearm/slackwarearm-current/][repository]].

  The packages required are:
  #+begin_src bash
    wpa_supplicant
    wireless_tools
    iw
    libnl3
  #+end_src

  After that the wireless interface can be configured as usual.

  It took me a while to install all the packages that I normally use and restore some of my configuration (dot files) but overall the process was quite pleasant, performance wise, it is ok, but struggles a bit playing YouTube videos, so I wouldn't recommend it as a desktop replacement. Maybe their new version with 8GB of RAM is more suitable for that, but at this point I already have too many RPis and can't justify buying another one. So my quest to replace my desktop with ARM continues...
